# Generated by Django 4.2.3 on 2023-07-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ECGRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tp9", models.IntegerField()),
                ("tp10", models.IntegerField()),
                ("af8", models.IntegerField()),
                ("af7", models.IntegerField()),
                ("right_aux", models.IntegerField()),
                ("output", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
