# Generated by Django 4.2.3 on 2023-07-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecg", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ecgrecord",
            name="af7",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="ecgrecord",
            name="af8",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="ecgrecord",
            name="right_aux",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="ecgrecord",
            name="tp10",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="ecgrecord",
            name="tp9",
            field=models.FloatField(),
        ),
    ]
